Add bookings
NovikSerg88/java-shareit pull request #2
Opened 2023-07-31 12:35 UTC by NovikSerg88

2023-08-01 21:16 UTC, sergeymamonov requested changes

2023-08-01 21:16 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/CommentMapper.java
> +    private final UserRepository userRepository;
Не нужно делать запросов к БД из класса конвертера. Класс должен выполнять одну функцию. Конвертер - конвертирует. Сервис - собирает и обрабатывает данные.

2023-08-01 21:16 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    private final UserRepository userRepository;
Отказаться от запросов к БД в конвертере.

2023-08-01 21:16 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    void deleteItemsForUser(long userId);
Проверьте, где вызываются этот метод и метод ниже?

2023-08-01 21:16 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingRequestDto.java
> +    private boolean isEndAfterStart() {
Не вижу, где используется этот метод.

2023-08-01 21:16 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/dto/BookingResponseDto.java
> +    public static class Item {
Здесь вы вводите новые сущности, хотя такие сущности уже есть в проекте. И получается дублирование. И это не очень хорошо, так как при изменении необходимо будет вносить изменение в два места. Поэтому лучше поискать решение без создания дублирующих сущностей.

2023-08-02 06:22 UTC, NovikSerg88 commented on src/main/java/ru/practicum/shareit/item/CommentMapper.java
> +    private final UserRepository userRepository;
Перенес репозитории из мапперов в сервисный слой.

2023-08-02 06:23 UTC, NovikSerg88 commented on src/main/java/ru/practicum/shareit/item/ItemMapper.java
> +    private final UserRepository userRepository;
Аналогично предыдущему замечанию.

2023-08-02 06:42 UTC, NovikSerg88 commented on src/main/java/ru/practicum/shareit/item/ItemService.java
> +    void deleteItemsForUser(long userId);
Добавил DELETE запросы в ItemController

2023-08-02 06:51 UTC, NovikSerg88 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingRequestDto.java
> +    private boolean isEndAfterStart() {
Насколько я понял спринг проверяет все аннотации валидации, включая и эту аннотацию, так как в контроллере прописана аннотация @Valid. Этим методом проверяю что время окончания бронирования после время старта.

2023-08-02 09:02 UTC, NovikSerg88 commented on src/main/java/ru/practicum/shareit/booking/dto/BookingResponseDto.java
> +    public static class Item {
Использовал новые Dto классы: BookerResponseDto, ItemResponseDto в которых оставил только те поля, которые требуются в ответе.

2023-08-03 04:53 UTC, sergeymamonov approved these changes

2023-08-03 05:08 UTC, merged