Add item requests
NovikSerg88/java-shareit pull request #3
Opened 2023-08-21 06:41 UTC by NovikSerg88

2023-08-22 17:52 UTC, sergeymamonov requested changes
В качестве улучшения классы dto можно сделать иммутабельными.

2023-08-22 17:52 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                            && (b.getStatus().equals(WAITING)
Метод equals необходимо вызывать у константы или у значения, которое гарантированно не равно null. Потому что если значение, у которого вызывается метод equals будет равно null, то получим NPE. Проверьте во всем коде, как вызывается метод equals.

2023-08-22 17:52 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +            List<Item> items = itemRepository.findAllByRequestId(itemRequest.getId());
Запросы к БД в цикле.

2023-08-22 17:52 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +            List<Item> items = itemRepository.findAllByRequestId(itemRequest.getId());
Запросы к БД в цикле.

2023-08-24 03:26 UTC, NovikSerg88 commented
> В качестве улучшения классы dto можно сделать иммутабельными.

Сделал dto классы иимутабельными.

2023-08-24 03:58 UTC, NovikSerg88 commented on src/main/java/ru/practicum/shareit/item/ItemServiceImpl.java
> +                            && (b.getStatus().equals(WAITING)
Спасибо. Поправил во всем коде.

2023-08-24 05:14 UTC, NovikSerg88 commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +            List<Item> items = itemRepository.findAllByRequestId(itemRequest.getId());
Добавил отдельный метод mapItemRequestToDto.

2023-08-24 05:36 UTC, NovikSerg88 commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +            List<Item> items = itemRepository.findAllByRequestId(itemRequest.getId());
Добавил отдельный метод mapItemRequestToDto.

2023-08-24 21:13 UTC, sergeymamonov requested changes

2023-08-24 21:13 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +                .map(this::mapItemRequestToDto)
От этого запросов к БД меньше не стало. Дело не в том, чтобы вынести что-то в отдельный метод в данном случае. А изменить логику, чтобы не было значительного количества запросов (не было запросов в цикле). Чем опасны запросы к БД в цикле. Пример, requests будет 1 тыс, и каждый запрос к цикле будет выполняться 0,01 с. То есть этот участок кода будет выполняться 10 с.

2023-08-24 21:13 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +                .map(this::mapItemRequestToDto)
Аналогично.

2023-08-24 21:15 UTC, sergeymamonov requested changes

2023-08-24 21:15 UTC, sergeymamonov commented on src/main/java/ru/practicum/shareit/booking/dto/BookerResponseDto.java
>      private Long id;
И поля еще можно сделать иммутабельными.

2023-08-29 07:04 UTC, NovikSerg88 commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +                .map(this::mapItemRequestToDto)
Не придумал ничего умнее как сделать отельные запросы для списка ItemRequestResponseDto и Items и затем работать с полученными списками.

2023-08-29 07:05 UTC, NovikSerg88 commented on src/main/java/ru/practicum/shareit/request/ItemRequestServiceImpl.java
> +                .map(this::mapItemRequestToDto)
Реализовал аналогично предыдущему методу.

2023-08-29 07:07 UTC, NovikSerg88 commented on src/main/java/ru/practicum/shareit/booking/dto/BookerResponseDto.java
>      private Long id;
Поля пока не устал делать final потому что многие тесты у меня завязаны на изменение свойств объекта во время теста. Учту в следующем ТЗ.

2023-08-30 04:10 UTC, sergeymamonov approved these changes

2023-08-30 05:05 UTC, merged